title: Some TeX Developments
description: Coding in the TeX world

author: Joseph Wright
email: joseph.wright@morningstar2.co.uk

plugins:
- jekyll-feed
- jekyll-sitemap

highlighter: rouge

remote_theme: ngzhio/jekyll-theme-hamilton
