title: Some TeX Developments

tagline: Coding in the TeX world
url: https://www.texdev.net

author: Joseph Wright
email: joseph.wright@morningstar2.co.uk

plugins:
   - jekyll-feed
   - jekyll-seo-tag
   - jekyll-sitemap

highlighter: rouge

remote_theme: ngzhio/jekyll-theme-hamilton
skin: daylight

# For the SEO plugin
twitter:
  username: texdevnet
  card: summary
social:
  name: Joseph Wright
  links:
    - https://twitter.com/texdevnet
    - https://github.com/josephwright
lang: en_GB
