title: Some TeX Developments

tagline: Coding in the TeX world
url: www.texdev.net

author: Joseph Wright
email: joseph.wright@morningstar2.co.uk

plugins:
- jekyll-feed
- jekyll-sitemap

highlighter: rouge

remote_theme: ngzhio/jekyll-theme-hamilton
